export const LIST_SELECTTYPE = {
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  INLINE: 'INLINE',
};

export const BUTTON_POSITION = {
  TOP: 'TOP',
  ROW: 'ROW',
  BOTTOM: 'BOTTOM',
};
export const BUTTON_INTERACTIVETYPE = {
  ACTION: 'ACTION',
  MODAL: 'MODAL',
  PAGE: 'PAGE',
  RIGHTDRAWER: 'RIGHTDRAWER',
};
export const BUTTON_MESSAGEPROMPTTYPE = {
  MESSAGE: 'MESSAGE',
  CONFIRM: 'CONFIRM',
  TOOLTIP: 'TOOLTIP',
};
export const BUTTON_RELATEDROWS = {
  NONE: 'NONE',
  SINGLE: 'SINGLE',
  MULTIPLE: 'MULTIPLE',
};
export const BUTTON_BINDPARAMETERTYPE = {
  NONE: 'NONE',
  KEY: 'KEY',
  KEYS: 'KEYS',
  SEVERAL: 'SEVERAL',
  CUSTOMIZE: 'CUSTOMIZE',
  ALL: 'ALL'
};
