export const LIST_SELECTTYPE = {
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  INLINE: 'INLINE',
};

export const BUTTON_POSITION = {
  TOP: 'TOP',
  ROW: 'ROW',
  BOTTOM: 'BOTTOM',
};
export const BUTTON_INTERACTIVETYPE = {
  MODAL: 'MODAL',
  PAGE: 'PAGE',
  REPLACE: 'REPLACE',
  REFRESH: 'REFRESH',
  RIGHTDRAWER: 'RIGHTDRAWER',
};
export const BUTTON_MESSAGEPROMPTTYPE = {
  MESSAGE: 'MESSAGE',
  CONFIRM: 'CONFIRM',
  TOOLTIP: 'TOOLTIP',
};
export const BUTTON_RELATEDATA = {
  NONE: 'NONE',
  SINGLE: 'SINGLE',
  MULTIPLE: 'MULTIPLE',
  FORM: 'FORM',
};
export const BUTTON_BINDPARAMETERTYPE = {
  NONE: 'NONE',
  KEY: 'KEY',
  KEYS: 'KEYS',
  SEVERAL: 'SEVERAL',
  CUSTOMIZE: 'CUSTOMIZE',
  ALL: 'ALL'
};
export const BUTTON_ACTIONTYPE = {
  REQUEST: 'REQUEST',
  ROUTER: 'ROUTER'
};
