/**
 * Created by vison on 16/10/31.
 */
export default {
  INPUT: 'INPUT',
  INPUTNUMBER: 'INPUTNUMBER',
  SELECT: 'SELECT',
  CASCADER: 'CASCADER',
  AUTOCOMPLETE: 'AUTOCOMPLETE',
  CHECKBOX: 'CHECKBOX',
  DATEPICKER: 'DATEPICKER',
  RADIO: 'RADIO',
  RATE: 'RATE',
  SLIDER: 'SLIDER',
  SWITCH: 'SWITCH',
  TIMEPICKER: 'TIMEPICKER',
  TRANSFER: 'TRANSFER',
  TREESELECT: 'TREESELECT',
  UPLOAD: 'UPLOAD'
};
