export App from './App';
export Home from './Home';
export SubPage from './SubPage';
export Loading from './loading';
export NotFound from './NotFound.js';
// export NotMatchType from './notMatchType';
// export ListView from './listView';
// export ListDetail from './listDetail';
export PageContainer from './pageContainer';
export Login from './login';
export Register from './login/register';
export FindPwd from './login/findPwd';
export Role from './role';
